name: Build & Publish 
description: 
inputs:
  ECR_REGISTRY:
    description: 'Registry to push images to'
    required: true
  ECR_REPO:  
    description: 'Repo (must already exist in the Registry )'
    required: true
  INPUT_TOKEN: 
    description: 'Authentication Token for the Repository'
    required: true
  IMAGE_TAG:
    description: 'Tag(s) for docker image'
    reqired: true
outputs:
  random-number: 
    description: Status for now
    value: 'OK'

runs:
  using: "composite"
  steps:
    - run: chmod +x ./gradlew && ./gradlew bootJar
      shell: bash
    - id: build-image
      run: |
        # Build a docker container and
        # push it to ECR
        echo "${INPUT_TOKEN}" | docker login -u AWS --password-stdin ${ECR_REGISTRY}
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
        echo "::set-output TAG=$IMAGE_TAG"
      shell: bash
